export interface RobloxGameItem {
  id: string;
  name: string;
  category: string;
  placeId: string;
  thumbnailUrl: string;
  isPopular?: boolean;
  tags?: string[];
}

export const ROBLOX_CDN_ICON = (placeId: string) => `/api/roblox/icon/${placeId}`;

export const POPULAR_ROBLOX_GAMES: RobloxGameItem[] = [
  {
    id: 'blox-fruits',
    name: 'Blox Fruits',
    category: 'Blox Fruits',
    placeId: '2753915549',
    thumbnailUrl: '/api/roblox/icon/2753915549',
    isPopular: true,
    tags: ['one piece', 'anime', 'fruta', 'pirata', 'sea 1', 'sea 2', 'sea 3', 'auto farm', 'esp', 'raid'],
  },
  {
    id: 'fisch',
    name: 'Fisch',
    category: 'Fisch',
    placeId: '16732694052',
    thumbnailUrl: '/api/roblox/icon/16732694052',
    isPopular: true,
    tags: ['pesca', 'fish', 'auto fish', 'vara', 'oceano', 'mar'],
  },
  {
    id: 'brookhaven',
    name: 'Brookhaven 🏡RP',
    category: 'Brookhaven',
    placeId: '4924922222',
    thumbnailUrl: '/api/roblox/icon/4924922222',
    isPopular: true,
    tags: ['rp', 'roleplay', 'cidade', 'casa', 'veiculo', 'troll'],
  },
  {
    id: 'blade-ball',
    name: 'Blade Ball',
    category: 'Blade Ball',
    placeId: '13772394625',
    thumbnailUrl: '/api/roblox/icon/13772394625',
    isPopular: true,
    tags: ['auto parry', 'espada', 'bola', 'pvp', 'esquiva', 'defesa'],
  },
  {
    id: 'rivals',
    name: 'RIVALS',
    category: 'Rivals',
    placeId: '17625359962',
    thumbnailUrl: '/api/roblox/icon/17625359962',
    isPopular: true,
    tags: ['fps', 'tiro', 'aimbot', 'esp', 'silent aim', '1v1'],
  },
  {
    id: 'pet-sim-99',
    name: 'Pet Simulator 99!',
    category: 'Pet Simulator 99',
    placeId: '8737899170',
    thumbnailUrl: '/api/roblox/icon/8737899170',
    isPopular: true,
    tags: ['pets', 'ps99', 'auto farm', 'moedas', 'gemas', 'huge', 'titan'],
  },
  {
    id: 'da-hood',
    name: 'Da Hood',
    category: 'Da Hood',
    placeId: '2788229376',
    thumbnailUrl: '/api/roblox/icon/2788229376',
    isPopular: true,
    tags: ['aimlock', 'lock', 'fly', 'god mode', 'armas', 'gangue', 'dinheiro'],
  },
  {
    id: 'strongest-battlegrounds',
    name: 'The Strongest Battlegrounds',
    category: 'Strongest Battlegrounds',
    placeId: '10449761463',
    thumbnailUrl: '/api/roblox/icon/10449761463',
    isPopular: true,
    tags: ['saitama', 'opm', 'pvp', 'combo', 'auto block', 'battlegrounds'],
  },
  {
    id: 'jujutsu-shenanigans',
    name: 'The Jujutsu Shenanigans',
    category: 'Jujutsu Shenanigans',
    placeId: '9391468976',
    thumbnailUrl: '/api/roblox/icon/9391468976',
    isPopular: true,
    tags: ['jjk', 'gojo', 'sukuna', 'infinito', 'dominio', 'luta', 'anime'],
  },
  {
    id: 'anime-vanguards',
    name: 'Anime Vanguards',
    category: 'Anime Vanguards',
    placeId: '16146832113',
    thumbnailUrl: '/api/roblox/icon/16146832113',
    isPopular: true,
    tags: ['tower defense', 'anime', 'unidades', 'auto farm', 'summon'],
  },
  {
    id: 'anime-defenders',
    name: 'Anime Defenders',
    category: 'Anime Defenders',
    placeId: '17017769292',
    thumbnailUrl: '/api/roblox/icon/17017769292',
    isPopular: true,
    tags: ['tower defense', 'defesa', 'unidades', 'gemas', 'auto start'],
  },
  {
    id: 'toilet-tower-defense',
    name: 'Toilet Tower Defense',
    category: 'Toilet Tower Defense',
    placeId: '13775256536',
    thumbnailUrl: '/api/roblox/icon/13775256536',
    isPopular: true,
    tags: ['ttd', 'skibidi', 'titan', 'cameraman', 'auto farm', 'tower'],
  },
  {
    id: 'murder-mystery-2',
    name: 'Murder Mystery 2',
    category: 'Murder Mystery 2',
    placeId: '142823291',
    thumbnailUrl: '/api/roblox/icon/142823291',
    isPopular: true,
    tags: ['mm2', 'assassino', 'sheriff', 'esp', 'pegar arma', 'faca', 'godly', 'coins'],
  },
  {
    id: 'arsenal',
    name: 'Arsenal',
    category: 'Arsenal',
    placeId: '286090443',
    thumbnailUrl: '/api/roblox/icon/286090443',
    isPopular: true,
    tags: ['fps', 'aimbot', 'esp', 'silent aim', 'kill all', 'armas'],
  },
  {
    id: 'bedwars',
    name: 'BedWars',
    category: 'BedWars',
    placeId: '6872265039',
    thumbnailUrl: '/api/roblox/icon/6872265039',
    isPopular: true,
    tags: ['cama', 'killaura', 'fly', 'speed', 'teleport', 'pvp', 'blocos'],
  },
  {
    id: 'doors',
    name: 'DOORS 👁️',
    category: 'Doors',
    placeId: '6516141723',
    thumbnailUrl: '/api/roblox/icon/6516141723',
    isPopular: true,
    tags: ['terror', 'monstros', 'portas', 'esp', 'auto complete', 'itens'],
  },
  {
    id: 'dress-to-impress',
    name: 'Dress To Impress',
    category: 'Dress To Impress',
    placeId: '14257134447',
    thumbnailUrl: '/api/roblox/icon/14257134447',
    isPopular: true,
    tags: ['dti', 'moda', 'roupas', 'vip', 'passarela', 'votos'],
  },
  {
    id: 'king-legacy',
    name: 'King Legacy',
    category: 'King Legacy',
    placeId: '4520749081',
    thumbnailUrl: '/api/roblox/icon/4520749081',
    isPopular: true,
    tags: ['one piece', 'anime', 'frutas', 'auto farm', 'bosses', 'esp'],
  },
  {
    id: 'slap-battles',
    name: 'Slap Battles',
    category: 'Slap Battles',
    placeId: '6403373529',
    thumbnailUrl: '/api/roblox/icon/6403373529',
    isPopular: true,
    tags: ['tapas', 'luva', 'gloves', 'slap farm', 'anti ragdoll', 'god mode'],
  },
  {
    id: 'sols-rng',
    name: "Sol's RNG",
    category: "Sol's RNG",
    placeId: '15552355651',
    thumbnailUrl: '/api/roblox/icon/15552355651',
    isPopular: true,
    tags: ['rng', 'auras', 'auto roll', 'biomas', 'pocoes', 'sorte'],
  },
  {
    id: 'type-soul',
    name: 'TYPE://SOUL',
    category: 'Type Soul',
    placeId: '14069678431',
    thumbnailUrl: '/api/roblox/icon/14069678431',
    isPopular: true,
    tags: ['bleach', 'shinigami', 'quincy', 'arrancar', 'bankai', 'farm'],
  },
  {
    id: 'adopt-me',
    name: 'Adopt Me!',
    category: 'Adopt Me',
    placeId: '920587237',
    thumbnailUrl: '/api/roblox/icon/920587237',
    isPopular: true,
    tags: ['pets', 'trade', 'bucks', 'auto farm', 'trocas', 'neon'],
  },
  {
    id: 'tower-of-hell',
    name: 'Tower of Hell',
    category: 'Tower of Hell',
    placeId: '1962086968',
    thumbnailUrl: '/api/roblox/icon/1962086968',
    isPopular: true,
    tags: ['toh', 'parkour', 'obby', 'teleport', 'god mode', 'anti ban'],
  },
  {
    id: 'deepwoken',
    name: 'Deepwoken',
    category: 'Deepwoken',
    placeId: '4111023553',
    thumbnailUrl: '/api/roblox/icon/4111023553',
    isPopular: true,
    tags: ['roguelike', 'rpg', 'esp', 'parry', 'mob farm', 'builds'],
  },
  {
    id: 'evade',
    name: 'Evade',
    category: 'Evade',
    placeId: '9872472334',
    thumbnailUrl: '/api/roblox/icon/9872472334',
    isPopular: true,
    tags: ['nextbot', 'revive', 'speed', 'auto farm', 'esp', 'sobrenatural'],
  },
  {
    id: 'bee-swarm',
    name: 'Bee Swarm Simulator',
    category: 'Bee Swarm Simulator',
    placeId: '1537690962',
    thumbnailUrl: '/api/roblox/icon/1537690962',
    isPopular: true,
    tags: ['abelhas', 'mel', 'polen', 'auto dig', 'macro', 'flores'],
  },
  {
    id: 'combat-warriors',
    name: 'Combat Warriors',
    category: 'Combat Warriors',
    placeId: '4282985734',
    thumbnailUrl: '/api/roblox/icon/4282985734',
    isPopular: true,
    tags: ['pvp', 'espadas', 'blood', 'aimbot', 'kill aura', 'parry'],
  },
  {
    id: 'counter-blox',
    name: 'Counter Blox',
    category: 'Counter Blox',
    placeId: '301549796',
    thumbnailUrl: '/api/roblox/icon/301549796',
    isPopular: true,
    tags: ['csgo', 'fps', 'aimbot', 'esp', 'wallhack', 'skins'],
  },
  {
    id: 'jailbreak',
    name: 'Jailbreak',
    category: 'Jailbreak',
    placeId: '606849621',
    thumbnailUrl: '/api/roblox/icon/606849621',
    isPopular: true,
    tags: ['policia', 'ladrao', 'auto rob', 'banco', 'joalheria', 'carros', 'speed'],
  },
  {
    id: 'grand-piece-online',
    name: 'Grand Piece Online (GPO)',
    category: 'Grand Piece Online',
    placeId: '1730877806',
    thumbnailUrl: '/api/roblox/icon/1730877806',
    isPopular: true,
    tags: ['gpo', 'one piece', 'frutas', 'krakens', 'dungeons', 'auto farm'],
  },
  {
    id: 'shindo-life',
    name: 'Shindo Life',
    category: 'Shindo Life',
    placeId: '4616652839',
    thumbnailUrl: '/api/roblox/icon/4616652839',
    isPopular: true,
    tags: ['naruto', 'shinobi', 'bloodlines', 'spins', 'bosses', 'auto farm'],
  },
  {
    id: 'ninja-legends',
    name: 'Ninja Legends',
    category: 'Ninja Legends',
    placeId: '3956818381',
    thumbnailUrl: '/api/roblox/icon/3956818381',
    isPopular: true,
    tags: ['ninja', 'auto swing', 'auto sell', 'shuriken', 'pets', 'ilhas'],
  },
  {
    id: 'prison-life',
    name: 'Prison Life',
    category: 'Prison Life',
    placeId: '155615604',
    thumbnailUrl: '/api/roblox/icon/155615604',
    isPopular: true,
    tags: ['prisao', 'armas', 'kill all', 'mod gun', 'criminoso', 'guarda'],
  },
  {
    id: 'natural-disaster',
    name: 'Natural Disaster Survival',
    category: 'Natural Disaster',
    placeId: '189707',
    thumbnailUrl: '/api/roblox/icon/189707',
    isPopular: true,
    tags: ['desastre', 'sobrevivencia', 'ilha', 'teleport', 'tsunami', 'tornado'],
  },
  {
    id: 'survive-killer',
    name: 'Survive the Killer!',
    category: 'Survive the Killer',
    placeId: '4589254888',
    thumbnailUrl: '/api/roblox/icon/4589254888',
    isPopular: true,
    tags: ['killer', 'assassino', 'esp', 'speed', 'resgatar', 'escape'],
  },
  {
    id: 'flee-facility',
    name: 'Flee the Facility',
    category: 'Flee the Facility',
    placeId: '893973440',
    thumbnailUrl: '/api/roblox/icon/893973440',
    isPopular: true,
    tags: ['hack', 'computador', 'beast', 'martelo', 'escapar', 'congelar'],
  },
  {
    id: 'dungeon-quest',
    name: 'Dungeon Quest',
    category: 'Dungeon Quest',
    placeId: '2414851778',
    thumbnailUrl: '/api/roblox/icon/2414851778',
    isPopular: true,
    tags: ['rpg', 'dungeon', 'espada', 'magia', 'boss', 'loot'],
  },
  {
    id: 'bloxburg',
    name: 'Welcome to Bloxburg',
    category: 'Bloxburg',
    placeId: '185655149',
    thumbnailUrl: '/api/roblox/icon/185655149',
    isPopular: true,
    tags: ['construir', 'casa', 'trabalho', 'dinheiro', 'entrega', 'pizza'],
  },
  {
    id: 'universal-script',
    name: 'Universal / Geral',
    category: 'Universal',
    placeId: '0',
    thumbnailUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
    isPopular: true,
    tags: ['todos os jogos', 'universal', 'admin', 'fly', 'speed', 'bhop', 'esp', 'dex', 'remote spy'],
  },
];

export const CATEGORIES_LIST = [
  'Universal',
  'Geral',
  'Blox Fruits',
  'Fisch',
  'Brookhaven',
  'Blade Ball',
  'Rivals',
  'Pet Simulator 99',
  'Da Hood',
  'The Strongest Battlegrounds',
  'The Jujutsu Shenanigans',
  'Anime Vanguards',
  'Anime Defenders',
  'Toilet Tower Defense',
  'Murder Mystery 2',
  'Arsenal',
  'BedWars',
  'DOORS',
  'Dress To Impress',
  'King Legacy',
  'Slap Battles',
  "Sol's RNG",
  'TYPE://SOUL',
  'Adopt Me!',
  'Tower of Hell',
  'Deepwoken',
  'Evade',
  'Bee Swarm Simulator',
  'Combat Warriors',
  'Counter Blox',
  'Jailbreak',
  'Grand Piece Online',
  'Shindo Life',
  'Ninja Legends',
  'Prison Life',
  'Natural Disaster',
  'Survive the Killer',
  'Flee the Facility',
  'Dungeon Quest',
  'Bloxburg',
  'Outros',
];
